version: "3.7"

services:
  database_tutoria:
    image: postgres
    container_name: database_tutoria
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=tutoria
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: tutoria
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_tutoria
    depends_on:
      - database_tutoria

volumes:
  pgdata:
    driver: local